version: '3'

services:
  nginx:
    container_name: nginx
    # image: nginx:stable-alpine
    build: ./requirements/nginx
    image: nginx
    depends_on:
      - mariadb
      - wordpress
    ports: 
      - 443:443
    volumes:
      - $HOME/data/wordpress:/var/www/html:delegated
    networks: 
      - inception
    # restart: unless-stopped
    
  mariadb:
    container_name: mariadb
    # restart: unless-stopped
    image: mariadb:latest
    # build: ./requirements/mariadb
    # image: mariadb
    env_file: .env
    # volumes:
    #   -$HOME/data/mariadb:/var/lib/mysql
    networks: 
      - inception

  wordpress:
    container_name: wordpress
    # restart: unless-stopped
    # image: php:7.4-fpm-alpine
    build: ./requirements/wordpress
    image: wordpress
    volumes:
      - $HOME/data/wordpress:/var/www/html:delegated
    networks: 
      - inception

networks:
  inception:
    driver: bridge

# volumes:
#   wordpress_data:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: $HOME/data/wordpress
  
#   mariadb_data:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: $HOME/data/mariadb

# docker-compose run --rm mariadb mariadb -hmariadb -uexample-user -p
# docker-compose run --rm wordpress (wp user list)